---
version: '3'
#########################################################################
# NOTE: This docker-compose should be interfaced only via the Makefile. #
#########################################################################
volumes:
  go-pkg:
  go-bin:

services:
  golang: &golang
    image: golang
    network_mode: bridge
    environment:
      - PROJECT
      - PACKAGE
      - SKIP_TEST
      - SKIP_LINT
      - CI
      - GITHUB_TOKEN
      - GPG_KEY
    working_dir: /go/src/${PACKAGE}
    volumes:
      - .:/go/src/${PACKAGE}
      - go-pkg:/go/pkg
      - go-bin:/go/bin

  make:
    <<: *golang
    entrypoint: make
